# Generated by Django 2.1.5 on 2019-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190304_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='cust_delete',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='cust_update',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
