# Generated by Django 2.1.5 on 2019-02-27 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(choices=[('AC', 'Action'), ('CM', 'Comedy'), ('DR', 'Drama'), ('HR', 'Horror')], max_length=2)),
                ('movie_language', models.CharField(max_length=300)),
                ('movie_price', models.IntegerField()),
                ('movie_year', models.DateField(blank=True, null=True)),
                ('rentedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.Movies')),
            ],
        ),
    ]
