# Generated by Django 2.1.5 on 2019-02-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190227_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
    ]
