# Generated by Django 2.1.5 on 2019-02-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movies_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cetegory',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
