# Generated by Django 2.1.5 on 2019-02-27 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movies_cetegory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cetegory',
        ),
    ]
