# Generated by Django 2.1.5 on 2019-02-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movies_cetegory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rentedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customers'),
        ),
    ]
