# Generated by Django 2.1.5 on 2019-03-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movies_movie_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_update',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
